[iOS 2주차 과제 정지원]
NOW-SOPT-iOS-Part/JungJiwon-assignment pull request #1
Opened 2024-04-19 09:40 UTC by codeJiwon

### 기본과제
- [ ] SnapKit을 사용해서 구현해주세요
- [ ] 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러를 아래와 같이 수정해주세요.
- [ ] 비활성화일 때는 제일 기본
- [ ]  아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼을 활성화해주세요.
- [ ] 활성화 된 로그인하기 버튼을 클릭했을 때, 아래와 같이 아이디를 데이터 전달해주세요
- [ ] 비밀번호 텍스트필드 default 값은 security가 적용이 되어 있어야 합니다.
- [ ] 눈 모양 버튼을 클릭 시, security를 해제해주세요!
- [ ] 글 삭제 버튼을 클릭 시, 아이디, 비밀번호 텍스트필드를 각각 클리어해주세요!

### 문제
- clear button 색상 변경 문제(tint color로 적용했는데 적용이 안됨)
- 눈 모양이 다른 텍스트필드로 가야지 클릭이 됨

### 계획
- 선택/심화과제는 다음주까지 꼭 구현하여 올리겠습니다!!

🎥시연영상

https://github.com/NOW-SOPT-iOS-Part/JungJiwon-assignment/assets/121231822/b4c07592-7616-4bd2-8446-815b74693f20

2024-04-21 20:30 UTC, meltsplit reviewed
안녕하세요! 🤖 코드리뷰봇 멜트스플릿입니다ㅎㅎ

UI 상세한 부분까지 놓치지 않는 디테일이 아주 좋았습니당 :)
코드를 보며 궁금했던 점 몇가지 남기고 갑니다

수고하셨어용 :)

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }()
UI컴포넌트들 선언시 `lazy` 키워드를 붙인 이유가 무엇인지 궁금해요!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }()
"Pretendard-SemiBold"와 같이 반복되는 상수들은 사용하기 쉽게 상수화 하면 좋을 것 같아요!
같은 코드리뷰조인 진웅님께서 자주 쓰이는 Font를 [UIFont+Extension.swift](34th-Sopt-Assignment/34th-Sopt-Assignment/Common/Extensions/.swift) 파일에 잘 정리 하신 것 같아요.
참고해보면 좋을 것 같습니다 :)

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }
함수를 역할에 따라 `setupViews()`와 `setupLayout()`으로 구분한 거 아주 좋습니다👍👍

추가로, 해당 함수들을 `viewDidLoad()`에서 호출하신 이유 듣고싶어요!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }
같은 코드 여러번 쓸 때 귀찮음을 느끼셨다면 아래와 같은 Extension 코드를 추가해보는 건 어떨까요?

### 꿀코드 구현부
```swift
extension UIView {
    func addSubviews(_ views: UIView...) {
        views.forEach {
            addSubview($0)
        }
    }
}
```

### 꿀코드 사용부
```swift
private func setupViews() {
      view.addSubviews(titleLabel, idTextField, ...생략,  createNicknameButton)
}
```

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +
이 코드는 setupview() 함수 내에 있는 게 통일성에 좋을 것 같아요!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }
토글에 따라 분기처리 한 부분 넘 좋아여~!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2Tests/iOS_Week2Tests.swift
> +}
Xcode에서 프로젝트 처음 만들때 Include Test 체크박스 선택하면 생성되는 테스트 파일이네용.
테스트 코드를 사용하지 않는 다면 선택해제 후 프로젝트 만드시는 거 추천드립니당~

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/WelcomeViewController.swift
> +    }
popViewController와 dismiss 차이가 뭔지 궁금해용!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/SceneDelegate.swift
> +}
코드로 구현하기 위해 window 설정하는 부분 좋습니당!

2024-04-21 20:30 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +        }
AutoLayout으로 잡을 때 width을 상수로 지정한다면,
추후 문자열이 길어지면 글자가 짤릴 수도 있을 것 같아용!
label은 자체적으로 width사이즈를 갖기에 width를 따로 지정하지 않아도 될 것 같아요!

2024-04-22 13:50 UTC, JinUng41 requested changes
과제 하시느라 고생하셨습니다. 👍👍
몇 가지 코드와 관련하여 수정 및 참고 사항들을 적어보았습니다. 확인해 보시고 궁금한 것 있으시면 또 코멘트 남겨주시면 좋을 것 같아요!
그리고 또 코드 로직 이외 몇 가지 더 말씀 드려 보자면,
1. '.DS_Store'를 gitignore를 활용하여 git에 추적되지 않도록 해보시면 좋을 것 같아요.
    - '.DS_Store'는 MacOS 시스템 적으로 파인더에 관한 정보들을 담고 있는 것으로 알고 있습니다.
    - gitignore.io를 이용한다면, 좀 더 쉽게 gitignore를 작성해 보실 수 있을 거에요. 참고해 보세요!
2. 코드가 정렬되지 않은 부분들이 보여요.
    - 깔끔한 코드 작성을 위해 정렬하는 습관 지켜주세요! ( 정렬한 구간을 드래그 후, Ctrl + i )
3. 커밋 단위를 좀 더 분리하면 어떨까요?
    - 저의 경우, 프로젝트 초기 설정을 관련하여 먼저 커밋 후, 기능 단위 커밋을 진행하는 편입니다.
    - 참고하시고 추후에 반영해 보시는 건 어떨까요? :)

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/Base.lproj/Main.storyboard
Code UI로 작성하신 것 같은데, 남겨두신 이유가 궁금합니다!

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +}
텍스트 필드에 삭제 버튼 기능을 확장하기 위한 것으로 보이는데요. 기능을 확장하기 위해서는 2가지 방법을 생각해 볼 것 같은데,

    1. 위와 같이 extension으로 확장하는 것
    2. UITextField를 상속한 커스텀 TextField를 구현하는 것

둘 중, extension을 통해 계산 속성을 구현하신 이유를 듣고 싶어요!

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +            return button
저 같은 경우, 이해하기 명확한 코드에 대해서 주석을 따로 남기지 않는 편인데요. 커밋 시에 고려해 보시면 좋을 것 같아요!

`if let` 구문의 경우, KVC (Key-Value-Coding)의 코드인 것 같은데, 제가 잘 몰라서 그러는데 알려주실 수 있으실까요?

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +class LoginViewController: UIViewController, UITextFieldDelegate {
저는 명확한 기능 분리와 이해를 위해 채택하는 프로토콜 별로 extension으로 분리하는 편인데요. MARK 주석과 같이 사용하여 해당 기능에 특정하여 바로 접근할 수 있었습니다. 고려해보시면 좋을 것 같아요!
```swift
final class LoginViewController: UIViewController {
    // 생략...
}

extension LoginViewController: UITextFieldDelegate {
    // 생략...
}
```

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/WelcomeViewController.swift
> +    }
해당 메서드를 통해, id를 받아오려 하신 것처럼 보여요. 그렇다면 id 프로퍼티는 접근 제어를 통해 외부에서 접근하지 못하도록 구현해 볼 것 같아요! 현재는 LoginViewController에서 WelcomeViewController를 보여줄 때, 2가지 방법 모두가 가능하기 때문에 하나만 선택해도 괜찮지 않을까 생각합니다.

2024-04-22 13:50 UTC, JinUng41 commented on iOS-Week2/iOS-Week2/WelcomeViewController.swift
> +}
커스텀 델리게이트 패턴을 구현하려 하신 것처럼 보여요.
하지만 코드를 찾아본 결과, 정의만 하시고 아직 채택하고 구현한 내용은 보이지 않는 것 같아요.
이렇게 된다면 WelcomeViewController의 delegate 프로퍼티에 `nil`이 할당되어 있어, 원활한 동작이 이루어지지 못할 것이라 판단되요.
좀 더 커스텀 델리게이트 패턴을 공부하시고 적용해 보시면 좋을 것 같습니다~

2024-04-22 14:22 UTC, codeJiwon commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +            return button
코드에서 버튼을 옵셔널로 설정하였는데, 옵셔널 값이 nil인지 아닌지 확인한 후 nil이 아닐 때만 실행되게 하는 구문입니다!

2024-04-22 14:26 UTC, codeJiwon commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +        }
아 그렇군요!! 세미나 시간에 label이 자체적으로 width 가진다고 배웠는데 다시 유념하겠습니다

2024-04-22 14:33 UTC, codeJiwon commented on iOS-Week2/iOS-Week2/WelcomeViewController.swift
> +    }
popViewController는 현재의 ViewController를 제거하고 이전 ViewController로 되돌아가고, dismiss는 모달 형식의 ViewController를 닫을 때 사용합니다. popViewController를 통해 WelcomeViewController에서 LoginViewController로 이동하는 걸 구현하고, else문에서는 dismiss를 통해 WelcomeViewController를 닫으려는 의도였습니다!

2024-04-22 14:37 UTC, codeJiwon commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }()
1주차 생각과제로 lazy var에 대해 공부했었는데요, lazy 키워드를 사용하면 필요할 때만 UI 요소를 초기화하여 성능을 향상시킬 수 있다하여 lazy 키워드를 붙였습니다.

2024-04-22 14:46 UTC, codeJiwon commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }
뷰컨트롤러가 로드되자마자 UI 요소들이 생성되고 배치되어야한다고 생각해서 viewDidLoad() 안에 호출했습니다. 굳이 viewDidLoad()에 배치하지 않아도 되었을까요?

2024-04-22 15:19 UTC, meltsplit commented on iOS-Week2/iOS-Week2/LoginViewController.swift
> +    }
아니용 저도 `viewDidLoad()`에다가 구현합니다. 이게 정답이라구 생각하기도 하구요ㅎ.ㅎ
다만 `init()`, `viewDidLoad()`, `viewWillAppear()`.. `viewDidAppear()`등 다양한 생명주기 함수가 있어서
각 ViewController 생명주기마다 어떤 함수를 호출하는 것이 좋을지 고민해보시면 좋을 것 같아서 여쭤봤슴다~

2024-04-22 15:39 UTC, meltsplit commented on iOS-Week2/iOS-Week2/WelcomeViewController.swift
> +    }
그렇다면 몇가지 질문 더 드려봅니다! 
저는 이번 풀리퀘에서 이 부분이 가장 중요한 부분이라고 생각들어서요
_(이번주 과제에서 **화면전환** 개념을 완벽히 이해하는게 추후 과제에 도움 되실 거에요!)_

1. WelcomeVC를 호출하는 ViewController는 어디인가요?
2. WelcomeVC를 화면에 띄울땐  `push` 방식을 사용하나요 `present` 방식을 사용하나요?
3. 위 코드에서 navigationController로 `if else` 문을 구분하신 이유는 무엇인가요?
4. navigationController가 무엇일까용?
5. LoginVC와 WelcomeVC는 navigationController에 속해있나요?
6. 위 코드의 `if let else` 구문에서 어느 코드가 수행될 것이라고 생각하시나요? (`if`문이 `참`인지 `거짓`인지)
7. `pop`과 `dismiss` 둘 다 사용해야할까요?


질문에 대한 답변을 남기실 필욘 없슴니다 그래도 꼭 고민해보셨으면 해요!
🤖 과제하시느라 수고하셨습니다 :)

2024-04-24 14:56 UTC, HELLOHIDI reviewed
코드리뷰를 수용하려고 하는 자세가 너무 멋진거 같아요! 지원이 고생햇어요!

2024-04-30 09:38 UTC, merged